# fly.toml app configuration file generated for skribble-scrab-frontend on 2026-04-13T14:00:56+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skribble-scrab-frontend'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
