import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { cn } from "~/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster
          position="bottom-right"
          gap={8}
          toastOptions={{
            classNames: {
              toast:
                "!rounded-none !border-2 !border-neutral-700 !bg-neutral-950 !text-neutral-100 !font-mono !shadow-none",
              error: "!border-red-500",
              title: "!font-bold !uppercase !tracking-widest !text-xs",
              description: "!font-mono !text-neutral-500 !text-xs !uppercase !tracking-wider",
              closeButton:
                "!rounded-none !border !border-neutral-700 !bg-neutral-900 !text-neutral-400 hover:!text-neutral-100",
            },
          }}
        />
      </body>
    </html>
  );
}
