// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GameResult struct {
	ID          int32              `json:"id"`
	RoomID      string             `json:"room_id"`
	PlayerID    string             `json:"player_id"`
	DisplayName string             `json:"display_name"`
	Score       int32              `json:"score"`
	PlayedAt    pgtype.Timestamptz `json:"played_at"`
}

type Word struct {
	ID       int32  `json:"id"`
	Word     string `json:"word"`
	Category string `json:"category"`
}
