// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"
)

const deleteRoomPlayer = `-- name: DeleteRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND player_id = $2
`

type DeleteRoomPlayerParams struct {
	RoomID   string `json:"room_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) DeleteRoomPlayer(ctx context.Context, arg DeleteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteRoomPlayer, arg.RoomID, arg.PlayerID)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, host_id, host_username, host_display_name, visibility, status, max_players, created_at, finished_at, name FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.HostUsername,
		&i.HostDisplayName,
		&i.Visibility,
		&i.Status,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Name,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :exec
INSERT INTO rooms (id, name, host_id, host_username, host_display_name, visibility, status, max_players)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, host_id, host_username, host_display_name, visibility, status, max_players, created_at, finished_at, name
`

type InsertRoomParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	HostID          string         `json:"host_id"`
	HostUsername    string         `json:"host_username"`
	HostDisplayName string         `json:"host_display_name"`
	Visibility      RoomVisibility `json:"visibility"`
	Status          RoomStatus     `json:"status"`
	MaxPlayers      int32          `json:"max_players"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) error {
	_, err := q.db.Exec(ctx, insertRoom,
		arg.ID,
		arg.Name,
		arg.HostID,
		arg.HostUsername,
		arg.HostDisplayName,
		arg.Visibility,
		arg.Status,
		arg.MaxPlayers,
	)
	return err
}

const insertRoomPlayer = `-- name: InsertRoomPlayer :exec
INSERT INTO room_players (room_id, player_id, username, display_name, role)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRoomPlayerParams struct {
	RoomID      string `json:"room_id"`
	PlayerID    string `json:"player_id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
}

func (q *Queries) InsertRoomPlayer(ctx context.Context, arg InsertRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, insertRoomPlayer,
		arg.RoomID,
		arg.PlayerID,
		arg.Username,
		arg.DisplayName,
		arg.Role,
	)
	return err
}

const listPublicRooms = `-- name: ListPublicRooms :many
SELECT id, host_id, host_username, host_display_name, visibility, status, max_players, created_at, finished_at, name FROM rooms
WHERE visibility = 'public' AND status = 'waiting'
ORDER BY created_at DESC
`

func (q *Queries) ListPublicRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listPublicRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.HostUsername,
			&i.HostDisplayName,
			&i.Visibility,
			&i.Status,
			&i.MaxPlayers,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomStatus = `-- name: UpdateRoomStatus :exec
UPDATE rooms
SET status      = $2,
    finished_at = CASE WHEN $2 = 'finished'::room_status THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateRoomStatusParams struct {
	ID     string     `json:"id"`
	Status RoomStatus `json:"status"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) error {
	_, err := q.db.Exec(ctx, updateRoomStatus, arg.ID, arg.Status)
	return err
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT room_id, player_id, username, display_name, role, joined_at FROM room_players WHERE room_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) ListRoomPlayers(ctx context.Context, roomID string) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomPlayer
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.PlayerID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
