// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: words.sql

package db

import (
	"context"
)

const getRandomWord = `-- name: GetRandomWord :one
SELECT word FROM words
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomWord(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getRandomWord)
	var word string
	err := row.Scan(&word)
	return word, err
}
